(define (double x) (+ x x))
(define (halve x) (/ x 2))
(define (even? x)
  (= (remainder x 2) 0))

(define (mul a b)
  (cond ((= a 0) 0)
        ((= b 0) 0)
        ((= a 1) b)
        ((= b 1) a)
        ((even? a) (double (mul (halve a)
                                b)))
        (else (+ b (double (mul (halve (- a 1))
                                b))))))

(mul 3 4)
(mul 4 4)
(mul 0 1)
(mul 9 9)
